version: '3'

volumes:
  pgdata:

services:
  broker-td:
    build:
      context: ./../broker-td
      dockerfile: ./../broker-td/broker-td.dockerfile
    restart: always
    ports:
      - "3000:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      PORT: 80
    user: '${UID}:${GID}'

  telegram-bot-service:
    build:
      context: ./../telegram-bot-service
      dockerfile: ../telegram-bot-service/telegram-bot-service.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    cap_add:
      - SYS_ADMIN
    depends_on:
      - user-service
    user: '${UID}:${GID}'

  user-service:
    build:
      context: ./../user-service
      dockerfile: ./../user-service/user-service.dockerfile
    restart: always
    ports:
      - "3001:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRE_DSN: "host=postgres-tbs port=5432 user=postgres password=password dbname=users_tbs sslmode=disable timezone=UTC connect_timeout=3"
      PORT: 80
      IS_DEVELOPMENT: "true"
      ACTIVATE_CRON: ""
    depends_on:
      - postgres-tbs
    user: '${UID}:${GID}'

  drive-service:
    build:
      context: ./../drive-service
      dockerfile: ./../drive-service/drive-service.dockerfile
    restart: always
    ports:
      - "5001:5001"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      PORT: 5001
    user: '${UID}:${GID}'

  postgres-tbs:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_tbs
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata/000001_init.up.sql:/docker-entrypoint-initdb.d/000001_init.up.sql
      - ./pgdata/000002_insert_default_users.up.sql:/docker-entrypoint-initdb.d/000002_insert_default_users.up.sql
      - ./pgdata/000003_alter_table_bot_user_is_parent_column.up.sql:/docker-entrypoint-initdb.d/000003_alter_table_bot_user_is_parent_column.up.sql
      - ./pgdata/000004_insert_default_bot_user_parent.up.sql:/docker-entrypoint-initdb.d/000004_insert_default_bot_user_parent.up.sql
    user: '${UID}:${GID}'
    healthcheck:
      test: pg_isready -U postgres -d users_tbs
      interval: 10s
      timeout: 3s
      retries: 5