version: '3.7'

services:
  broker-td:
    image: ferch5003/broker-td:1.0.4
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "3000:80"
    restart: unless-stopped
    env_file:
      - ./broker-td/.env
    networks:
      - caddy_server_default

  telegram-bot-service:
    image: ferch5003/telegram-bot-service:1.0.5
    deploy:
      mode: replicated
      replicas: 1
    restart: unless-stopped
    env_file:
      - ./telegram-bot-service/.env
    depends_on:
      - user-service
      - broker-td
    networks:
      - caddy_server_default

  user-service:
    image: ferch5003/user-service:1.0.4
    ports:
      - "3001:80"
    deploy:
      mode: replicated
      replicas: 1
    restart: unless-stopped
    env_file:
      - ./user-service/.env
    networks:
      - caddy_server_default

  drive-service:
    image: ferch5003/drive-service:1.0.4
    ports:
      - "5001:5001"
    deploy:
      mode: replicated
      replicas: 1
    restart: unless-stopped
    env_file:
      - ./drive-service/.env
    networks:
      - caddy_server_default

networks:
  caddy_server_default:
    external: true