version: '3'

volumes:
  caddy_data:
    external: true
  caddy_config:

services:
  caddy:
    image: ferch5003/tfd-micro-caddy-production:1.0.1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == drive-files-tracker
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  broker-td:
    image: ferch5003/broker-td:1.0.2
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      PORT: 80

  telegram-bot-service:
    image: ferch5003/telegram-bot-service:1.0.2
    deploy:
      mode: replicated
      replicas: 1
    restart: unless-stopped
    depends_on:
      - user-service
      - broker-td

  user-service:
    image: ferch5003/user-service:1.0.2
    ports:
      - "3001:80"
    deploy:
      mode: replicated
      replicas: 1
    restart: unless-stopped
    environment:
      PORT: 80
      IS_DEVELOPMENT: ""
      ACTIVATE_CRON: "true"

  drive-service:
    image: ferch5003/drive-service:1.0.2
    ports:
      - "5001:5001"
    deploy:
      mode: replicated
      replicas: 1
    restart: unless-stopped
    environment:
      PORT: 5001