version: '3'

volumes:
  pgdata:

services:
  broker-td:
    image: ferch5003/broker-td:1.0.3
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "3000:80"
    env_file:
      - ./../broker-td/.env
    networks:
      - dft_app_default
      - caddy_network

  telegram-bot-service:
    image: ferch5003/telegram-bot-service:1.0.5
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ./../telegram-bot-service/.env
    depends_on:
      - user-service
      - broker-td
    networks:
      - dft_app_default
      - caddy_network

  user-service:
    image: ferch5003/user-service:1.0.3
    ports:
      - "3001:80"
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ./../user-service/.env
    networks:
      - dft_app_default
      - caddy_network

  drive-service:
    image: ferch5003/drive-service:1.0.3
    ports:
      - "5001:5001"
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ./../drive-service/.env
    networks:
      - dft_app_default
      - caddy_network

networks:
  dft_app_default:
    driver: overlay
  proxy:
    external: true